### PR TITLE
fix(ManagedSpyLib): Fix issue on Win32Exception and AccessDenied

### PR DESCRIPTION
**Pull request by uian2000**
I think this PR fixs Issue#12

Exception occurs on my x64 os, nither run x64 nor x32 version, without admin rights.
I've found the reason beside this method: IsManagedProcess.
So I add a new function IsProcessInteractive to exam target process.

### CODE REVIEW

**Comment by ForNeVeR** [comment]
Hello! Sorry, I'm not sure if I'll have enough time to review that PR tomorrow. Please stay tuned, I'll review it and (hopefully) merge in the nearest 48 hours.

Thanks for the PR!

**Comment by uian2000** [comment]
That would be fine.

**Comment by ForNeVeR** [comment]
@uian2000 I've merged your changes, and I have some recommendations for productive interaction in future (not only with me, but that's a general recommendations for you as a GitHub contributor):

1. Please don't make commits such as 26b730b46804e97059ae3ad1a41624b0a1af0133 without additional consultation with the repository maintainer (in that case, me). At first, your commit looked okay to me, but it turned out that it slightly messed up the release process. I haven't merged it.

   If you have any useful changes in the project build and/or release process — then, _please_, first discuss them in an issue tracker, and _then_ make any changes.

2. Currently you're making all your pull requests from your `develop` branch to my `develop` branch. While that's okay for one-shot pull requests (when you make a single contribution and never contribute to the same project again), that's against general recommendation. The general rule is: _make a new branch for every new pull request_. That way you can make multiple simultaneous pull requests and add commits to any of them without messing anything.

Please don't take my recommendations offensive. I'm looking forward in working with you, and these are just a friendly advices. You're doing a good work!

**Comment by uian2000** [comment]
It's very kind of you for giving these recommendations.
I'll take that on my future PRs.
 do conversation, make new branch, commit, push, pull request.
Thank you very much, for my take advantage with your work!

**Pull request merged**
